export const REQUEST_GET_USER_DATA = 'USER/REQUEST_GET_USER_DATA'
export const GET_USER_DATA_SUCCESS = 'USER/GET_USER_DATA_SUCCESS'
export const GET_USER_DATA_FAILURE = 'USER/GET_USER_DATA_FAILURE'

export const CHECK_ROUTE_AUTH = 'USER/CHECK_ROUTE_AUTH'
export const AUTH_CHECKED = 'USER/AUTH_CHECKED'

export const USER_UPDATE_DATA_SUCCESS = 'USER/USER_UPDATE_DATA_SUCCESS'
export const USER_UPDATE_DATA_FAILURE = 'USER/USER_UPDATE_DATA_FAILURE'
export const REQUEST_UPDATE_USER_DATA = 'USER/REQUEST_UPDATE_USER_DATA'

export const UPLOAD_AVATAR_IMAGE_URL = 'USER/UPLOAD_AVATAR_IMAGE_URL'