export const REQUEST_GET_CHANNELS = 'CHANNELS/REQUEST_GET_CHANNELS'
export const GET_CHANNELS_SUCCESS = 'CHANNELS/GET_CHANNELS_SUCCESS'
export const GET_CHANNELS_FAILURE = 'CHANNELS/GET_CHANNELS_FAILURE'

export const REQUEST_ADD_CHANNEL = 'CHANNELS/REQUEST_ADD_CHANNEL'
export const ADD_CHANNEL_SUCCESS = 'CHANNELS/ADD_CHANNEL_SUCCESS'
export const ADD_CHANNEL_FAILURE = 'CHANNELS/ADD_CHANNEL_FAILURE'

export const REQUEST_REMOVE_CHANNEL = 'CHANNELS/REQUEST_REMOVE_CHANNEL'
export const REMOVE_CHANNEL_SUCCESS = 'CHANNELS/REMOVE_CHANNEL_SUCCESS'
export const REMOVE_CHANNEL_FAILURE = 'CHANNELS/REMOVE_CHANNEL_FAILURE'

export const REQUEST_REPLACE_CHANNEL = 'CHANNELS/REQUEST_REPLACE_CHANNEL'
export const REPLACE_CHANNEL_SUCCESS = 'CHANNELS/REPLACE_CHANNEL_SUCCESS'
export const REPLACE_CHANNEL_FAILURE = 'CHANNELS/REPLACE_CHANNEL_FAILURE'