export const REQUEST_FILE_UPLOAD = 'FILE_UPLOAD/REQUEST_FILE_UPLOAD'
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD/FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_FAILURE = 'FILE_UPLOAD/FILE_UPLOAD_FAILURE'

export const REQUEST_GET_UPLOADED_FILE_URL = 'FILE_UPLOAD/REQUEST_UPLOADED_FILE_URL'
export const GET_UPLOADED_FILE_URL_SUCCESS = 'FILE_UPLOAD/GET_UPLOADED_FILE_URL_SUCCESS'
export const GET_UPLOADED_FILE_URL_FAILURE = 'FILE_UPLOAD/GET_UPLOADED_FILE_URL_FAILURE'
