export const REQUEST_LOGIN = 'AUTH/REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'AUTH/LOGIN_FAILURE'

export const REQUEST_REGISTER = 'AUTH/REQUEST_REGISTER'
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'AUTH/REGISTER_FAILURE'
